# 베이스 이미지로 Python 3.10을 사용
FROM python:3.10 AS study_python_env

# 작업 디렉토리 설정
WORKDIR /app

# 필요 라이브러리 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# FastAPI 서버 실행
CMD ["uvicorn", "main_v1:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
